spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/hipchon;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernae:
        #얘는 sys out으로 찍음 - 운영시 안쓴다
#        show_sql: true
#        format_sql: true
logging:
  level:
    #logger로 찍음
    org.hibernate.SQL: debug
    org.hibernate.type: trace

