spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/hipchon
    username: hipchon
    password: hipchon
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernae:
        #얘는 sys out으로 찍음 - 운영시 안쓴다
        show_sql: true
        format_sql: true
logging:
  level:
    #logger로 찍음
    org.hibernate.SQL: debug
    org.hibernate.type: trace
